### ISSUE TITLE
Low Quality capture

### ISSUE THREAD

**Issue by MySt1KxSyL3nT** [getsocial-im/getsocial-capture#1]
Hello,

When replaying a capture, it is a *very* low quality (like 240p on youtube), while digging in the code, the only thing I saw related to this was `RenderTextureFormat` in the `Recorder`class, however, tweaking it does not seem to work.

Any ideas/tips or known bugs about this?

Specs:
2D project
Unity 2018.3.2f1
Bug seen on Android/iOS/OSXEditor

**Comment by gaborvass** [comment]
Hi,

Preview is created of a sequence of screenshots. The screenshot size is 1/4th of the original screen size in pixels, so it could cause the quality drop issue. You can change this parameter in `Recorder.cs`, line 65/66.
Could you attach a screenshot to see how the quality issue looks like? Thanks!

**Comment by MySt1KxSyL3nT** [comment]
Hi gaborvass,

Thanks for the answer, I managed to find and change this default behaviour, moreover, while digging and using your asset, I managed to fix some memory leaks due to RenderTexture2Ds that are never release by the Garbage Collector.

Do you accept Pull Request? So I can share with you my fix !

**Comment by gaborvass** [comment]
Hi,

Of course, we accept PR's! Please create one and we'll review and hopefully merge it. Thanks in advance for taking the time to make it better!

**Comment by MySt1KxSyL3nT** [comment]
Perfect, the pull request is available here:

https://github.com/getsocial-im/getsocial-capture/pull/3
