### ISSUE TITLE
Blur Gif

### ISSUE THREAD

**Issue by Pankti16** [getsocial-im/getsocial-capture#6]
The generated gif looks so blur, how can I fix it?

**Comment by gaborvass** [comment]
Hi,
By default not the original screen size is captured:
```
_width = _camera.pixelWidth / 4;
_height = _camera.pixelHeight / 4;
```
Please change the above settings in `Recorder.cs` file in order to improve the quality. Take in mind that changing these values will affect the final gif size.

**Comment by Pankti16** [comment]
Thanks for your reply, already found it.
