### ISSUE TITLE
NullReferenceException in Start

### ISSUE THREAD

**Issue by Marioyahuar** [getsocial-im/getsocial-capture#9]
Hi!

First of all, thank you very much for the plugin, it does exactly what i needed.

However, I have a problem I was unable to solve: 
Every time I enable the prefab "GetSocialCapturePreview", I get this Error Message in Console:

NullReferenceException: Object reference not set to an instance of an object
GetSocialSdk.Capture.Scripts.GetSocialCapturePreview.Init () (at Assets/Plugins/GetSocialCapture/Scripts/GetSocialCapturePreview.cs:68)
GetSocialSdk.Capture.Scripts.GetSocialCapturePreview.Start () (at Assets/Plugins/GetSocialCapture/Scripts/GetSocialCapturePreview.cs:101)

In Unity Editor, the app stops due the error, but If I press Play to continue, everything else works just ok. In Android, it just seems to ignore the error.

I have not make any change in Plugin Scripts. If you need any aditional Info please tell me.

Thank you very much,
Greetings.

**Comment by hydro0** [comment]
Hey! Thank you for reporting the issue. Which Unity version do you use?

**Comment by Marioyahuar** [comment]
Hi

I'm using version 2019.2.9f1

**Comment by hydro0** [comment]
Thanks. Could you please try to add `if (StoreWorker.Instance.StoredFrames == null) return;` to the line `68` of `GetSocialCapturePreview.cs` in `Init()` method and check if it helps?

**Comment by Marioyahuar** [comment]
Hi

Thank you very much, this solve the issue. Thanks for the quick support. 

Greetings
